module.exports = {
	siteTitle: "MIRA",
	conTitle: 'MSAC Integrated Reporting Application',
	siteDesc: 'The MSAC Web Tool',
	keyNameM: 'MIRAMenu',
	keyNameBU: 'BusinessUnit',
	keyIntCal: 'calendaridall',
	msgIdPassR: 'IBM Intranet ID and/or password is required',
	msgIdPassW: 'Wrong IBM Intranet ID and/or password.',
	facesURLcn: 'https://faces.tap.ibm.com/api/find/?q=%t',
	facesURLmail: 'https://faces.tap.ibm.com/api/find/?q=%t',
	bpURL: 'https://bluepages.ibm.com/BpHttpApisv3/slaphapi?ibmperson/(%f=%t).search/byjson',
	bpOrgURL: 'https://bluepages.ibm.com/BpHttpApisv3/slaphapi?ibmorganization/hrOrganizationCode=%t.search/byjson',
	bpDivURL: 'https://bluepages.ibm.com/BpHttpApisv3/slaphapi?ibmdivdept/dept=%t.search/byjson',
	bgURL: 'https://bluepages.ibm.com/tools/groups/groupsxml.wss?task=listMembers&attrib=%f&group=%t',
	addMembersURL: 'https://bluepages.ibm.com/tools/groups/protect/groups.wss?gName=%g&task=Members&mebox=%u&Select=Add+Members&API=1',
	delMembersURL: 'https://bluepages.ibm.com/tools/groups/protect/groups.wss?gName=%g&task=DelMem&mebox=%u&Delete=Delete+Checked&API=1 ',
	mirainterfaces: 'https://mira-connector-dev.w3ibm.mybluemix.net',
	maxElementsPerView : 1000
}
